### PR TITLE
Fix exiting wrapper

### LINKED ISSUE #13: windows-terminal-quake doesn't start both the terminal and itself. (exception thrown: process is null)
Hey @flyingpie, thanks a lot for creating this. I was so very happy to find this plugin. I'm sure I will be using this all the time like I did in Cmder.

I've downloaded `v0.5` (also  tried `v0.4`) and read the readme, but could not find how it is supposed to open both terminal and this plugin at the same time. I had hoped there would be some setting that allows the plugin to start with terminal automatically.

### Expected behaviour

Option 1:

- Open terminal executable
- See that terminal + quake style plugin work
- This clearly documented in the readme

Option 2;

- Open `windows-terminal-quake` executable
- See that terminal + quake style plugin work
- This clearly documented in the readme

#### First scenario worked perfectly;

- Open terminal
- Added executable and the config to `"C:\Users\(username)\"`
- Open `windows-terminal-quake.exe`
- See that it works! awesome.

#### But now I'd like the plugin to automatically start;

- Close terminal
- Open terminal again 
- See that quake style no longer works (which essentially just means that nothing was "installed")

#### So I'm thinking perhaps I should just open terminal with the executable;

- Close terminal
- Open `windows-terminal-quake.exe` 
- See a non-maximised terminal window without the plugin enabled.
- Open `windows-terminal-quake.exe` again with the window already open
- See that now it works.

### Considered solutions

I tried looking in the following places for clues how to make it work out of the box:

- The readme of this repository
- This plugins configuration
- The configuration file from Terminal

### Reason for starting both with 1 executable

- General convenience
- Opening it when clicking the terminal tab within an IDE will not work if there are two executable files to be called (I'm looking to replace Cmder now quake style is here for terminal)

image

Thanks again for your great work.

### PR DESCRIPTION
**Pull request by webbertakken**
First iteration towards solving the problem described in #13

The problem seemed to be that the process that starts the Windows Terminal itself is terminating, after which the process with name `WindowsTerminal` becomes available.

This pull request makes the process is always started and correctly selected as well.

Fixes #13

### CODE REVIEW

File: windows-terminal-quake/Program.cs [hunk 1]
```diff
@@ -30,10 +32,16 @@ public static void Main(string[] args)
...
+							WindowStyle = ProcessWindowStyle.Maximized,
+							CreateNoWindow = true,
 						}
 					};
 					process.Start();
+					process = Process.GetProcessesByName("WindowsTerminal").First();
+					process.WaitForInputIdle();
+					process.Refresh();
+					Log.Logger.Information("process was started from quake console (to be tested values)");
+					LogProcessInformation(process);
```
Comment (webbertakken) [inline windows-terminal-quake/Program.cs:44]: When I take this part out, it'll actually still show the behaviour like in the video I made.

Perhaps there is a race condition between the process initialising and the toggler trying to get its `mainWindowHandle`?

**Comment by webbertakken** [comment]
@flyingpie please review. Let me know if I should change anything else.
